import React from 'react';
import { Link } from 'react-router-dom';
import { Scale, BookOpen, AlertTriangle, UserCheck, ExternalLink, ArrowLeft } from 'lucide-react';
import Navbar from '../components/layout/Navbar';
import Footer from '../components/layout/Footer';

const TermsPage = () => {
  return (
    <div className="min-h-screen bg-[#F4F2EE] flex flex-col font-sans">
      <Navbar />

      <main className="flex-1 max-w-4xl w-full mx-auto px-4 sm:px-6 py-8 sm:py-12">
        {/* Back Link */}
        <Link
          to="/"
          className="inline-flex items-center gap-1.5 text-xs font-bold text-linkedin-text-secondary hover:text-linkedin-blue mb-6 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to CareerLens Home</span>
        </Link>

        {/* Terms Header Card */}
        <div className="bg-white border border-linkedin-border rounded-2xl p-6 sm:p-10 shadow-xs mb-8">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 text-linkedin-blue text-xs font-bold mb-4">
            <Scale className="w-4 h-4" />
            <span>Platform Agreement</span>
          </div>

          <h1 className="text-2xl sm:text-4xl font-extrabold text-linkedin-text-primary tracking-tight">
            Terms of Service
          </h1>

          <p className="text-xs sm:text-sm text-linkedin-text-secondary mt-3 leading-relaxed">
            Welcome to CareerLens. Please read these terms carefully before using our platform to discover career opportunities across tech, business, and creative fields, calculate match scores, and track your applications.
          </p>

          <div className="mt-4 pt-4 border-t border-gray-100 flex flex-wrap items-center gap-6 text-xs text-linkedin-text-muted">
            <span><strong>Effective Date:</strong> August 25, 2026</span>
            <span><strong>Version:</strong> 1.0</span>
          </div>
        </div>

        {/* Content Sections */}
        <div className="space-y-6 text-linkedin-text-primary text-sm sm:text-base leading-relaxed">
          {/* Section 1: Overview of Services */}
          <section className="bg-white border border-linkedin-border rounded-xl p-6 sm:p-8 shadow-2xs space-y-3">
            <div className="flex items-center gap-2 text-linkedin-blue font-bold text-lg">
              <BookOpen className="w-5 h-5" />
              <h2>1. Scope of Services</h2>
            </div>
            <p className="text-xs sm:text-sm text-linkedin-text-secondary">
              CareerLens provides AI-assisted resume skill extraction, aggregated job search discovery, deterministic fit scoring algorithms, personalized skill-gap roadmaps, and application pipeline management.
            </p>
          </section>

          {/* Section 2: Informational Nature of AI Match Scoring */}
          <section className="bg-white border border-linkedin-border rounded-xl p-6 sm:p-8 shadow-2xs space-y-3">
            <div className="flex items-center gap-2 text-amber-700 font-bold text-lg">
              <AlertTriangle className="w-5 h-5" />
              <h2>2. Informational Disclaimer for AI Features</h2>
            </div>
            <p className="text-xs sm:text-sm text-linkedin-text-secondary leading-relaxed">
              Match scores, readiness percentages, and learning roadmaps generated by CareerLens are informational tools designed to assist your job exploration. They do not constitute official hiring guarantees, employer evaluations, or certified legal/career advisory.
            </p>
          </section>

          {/* Section 3: Third-Party Job Listings & External Applications */}
          <section className="bg-white border border-linkedin-border rounded-xl p-6 sm:p-8 shadow-2xs space-y-3">
            <div className="flex items-center gap-2 text-linkedin-blue font-bold text-lg">
              <ExternalLink className="w-5 h-5" />
              <h2>3. External Job Listings & Employer Links</h2>
            </div>
            <p className="text-xs sm:text-sm text-linkedin-text-secondary leading-relaxed">
              Job opportunities displayed on CareerLens may be imported from third-party aggregators (such as Adzuna) and direct employer links. CareerLens is not responsible for the hiring decisions, accuracy, availability, or interview processes of third-party employers.
            </p>
          </section>

          {/* Section 4: User Responsibilities */}
          <section className="bg-white border border-linkedin-border rounded-xl p-6 sm:p-8 shadow-2xs space-y-3">
            <div className="flex items-center gap-2 text-linkedin-blue font-bold text-lg">
              <UserCheck className="w-5 h-5" />
              <h2>4. User Responsibilities & Acceptable Use</h2>
            </div>
            <ul className="list-disc pl-5 text-xs sm:text-sm text-linkedin-text-secondary space-y-2">
              <li>You agree to only upload resumes and credentials that you own or have the lawful right to provide.</li>
              <li>You agree to maintain the confidentiality of your account credentials.</li>
              <li>You agree not to scrape, reverse engineer, or abuse the platform through automated bot traffic.</li>
            </ul>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default TermsPage;
